#!/bin/bash
#PBS -A hep105
#PBS -N label_test
#PBS -l walltime=00:30:00
#PBS -l nodes=1
#PBS -j oe
#PBS -V

cd $PROJWORK/hep105/steven_caffe2/caffe
source $MODULESHOME/init/bash
source $PROJWORK/hep105/steven_caffe2/bashsetup.execenv.sh

# comment out for Rhea
module load cray-mpich

TOOLS=./build/tools

aprun -n 1 -N 1 $TOOLS/caffe train \
  --solver=/lustre/atlas/proj-shared/hep105/caffe_titan/test/solver.txt
