#!/bin/bash
#PBS -A hep105
#PBS -N xview_127x50
#PBS -l walltime=2:00:00
#PBS -l nodes=1
#PBS -j oe
#PBS -V

cd $PROJWORK/hep105/steven_caffe2/caffe
source $MODULESHOME/init/bash
source $PROJWORK/hep105/steven_caffe2/bashsetup.execenv.sh

# comment out for Rhea
module load cray-mpich

TOOLS=./build/tools

aprun -n 1 -N 1 $TOOLS/caffe train \
  --solver=/lustre/atlas/proj-shared/hep105/caffe_titan/minosmatch_nukecczdefs_127x50_x_unshifted_me1Bmc_solver.prototxt

#aprun -n 1 -N 1 $TOOLS/caffe train \
#  --solver=/lustre/atlas/proj-shared/hep105/caffe_titan/minosmatch_nukecczdefs_127x50_x_unshifted_me1Bmc_solver.prototxt \
#  --snapshot=/lustre/atlas/proj-shared/hep105/caffe_test/minosmatch_nukecczdefs_127x50_x_unshifted_me1Bmc_model_iter_5000.solverstate
