#!/bin/bash
#PBS -A hep105
#PBS -l nodes=1
#PBS -l walltime=00:10:00
#PBS -N epsilon_inv_2016-05-30T07.39.00.897234_1_updater
#PBS -o /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_inv_2016-05-30T07.39.00.897234_updater.out
#PBS -j oe
#PBS -m n
cd /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs
python /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/mlmpr_caffe_depend.py advance --status /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_inv_2016-05-30T07.39.00.897234.ini
