#!/bin/bash
#PBS -A hep105
#PBS -l nodes=1
#PBS -l walltime=02:00:00
#PBS -N epsilon_xuv_2016-05-29T11.13.49.302090_4
#PBS -o /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_xuv_2016-05-29T11.13.49.302090_4.out
#PBS -j oe
#PBS -m n
qsub -W depend=afternotok:$PBS_JOBID /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_xuv_2016-05-29T11.13.49.302090_updater.pbs
source $MODULESHOME/init/bash
source $PROJWORK/hep105/steven_caffe2/bashsetup.execenv.sh
module load cray-mpich
cd /lustre/atlas/proj-shared/hep105/steven_caffe2/caffe
command time -v aprun -n 1 -N 1 ./build/tools/caffe train --solver=/lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_xuv_2016-05-29T11.13.49.302090.solver --snapshot=/lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/snapshots/epsilon_xuv_2016-05-29T11.13.49.302090_iter_45000.solverstate
