#!/bin/bash
#PBS -A hep105
#PBS -l nodes=1
#PBS -l walltime=02:00:00
#PBS -N epsilon_noada_2016-05-30T07.36.54.892099_18
#PBS -o /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_noada_2016-05-30T07.36.54.892099_18.out
#PBS -j oe
#PBS -m n
qsub -W depend=afternotok:$PBS_JOBID /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_noada_2016-05-30T07.36.54.892099_updater.pbs
source $MODULESHOME/init/bash
source $PROJWORK/hep105/steven_caffe2/bashsetup.execenv.sh
module load cray-mpich
cd /lustre/atlas/proj-shared/hep105/steven_caffe2/caffe
command time -v aprun -n 1 -N 1 ./build/tools/caffe train --solver=/lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_noada_2016-05-30T07.36.54.892099.solver --snapshot=/lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/snapshots/epsilon_noada_2016-05-30T07.36.54.892099_iter_425000.solverstate
