#!/bin/bash
#PBS -A hep105
#PBS -l nodes=1
#PBS -l walltime=00:10:00
#PBS -N epsilon_xuv_2016-05-29T11.13.49.302090_1_updater
#PBS -o /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_xuv_2016-05-29T11.13.49.302090_updater.out
#PBS -j oe
#PBS -m n
cd /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs
python /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/mlmpr_caffe_depend.py advance --status /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_xuv_2016-05-29T11.13.49.302090.ini
