#!/bin/bash
#PBS -A hep105
#PBS -l nodes=1
#PBS -l walltime=00:10:00
#PBS -N epsilon_noada_2016-05-30T07.36.54.892099_1_updater
#PBS -o /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_noada_2016-05-30T07.36.54.892099_updater.out
#PBS -j oe
#PBS -m n
cd /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs
python /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/mlmpr_caffe_depend.py advance --status /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_noada_2016-05-30T07.36.54.892099.ini
