#!/bin/bash
#PBS -A hep105
#PBS -l nodes=1
#PBS -l walltime=00:10:00
#PBS -N epsilon_lr001_2016-05-29T18.24.51.314592_1_updater
#PBS -o /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_lr001_2016-05-29T18.24.51.314592_updater.out
#PBS -j oe
#PBS -m n
cd /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs
python /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/mlmpr_caffe_depend.py advance --status /lustre/atlas/proj-shared/hep105/caffe_titan/caffe_workflow/xuv/logs/epsilon_lr001_2016-05-29T18.24.51.314592.ini
